INSERT INTO PRODUCT (PRO_ID,PRO_NAME,PRO_DESC,CAT_ID) VALUES
(1,"GTA V","Windows 7 and above with i5 processor and 8GB RAM",
(select CUS_ID from customer where CUS_PHONE="9785463215")),
(2,"TSHIRT","SIZE-L with Black, Blue and White variations",
(select CUS_ID from customer where CUS_PHONE="7895999999")),
(3,"ROG LAPTOP","Windows 10 with 15inch screen, i7 processor, 1TB SSD",
(select CUS_ID from customer where CUS_PHONE="9994562399")),
(4,"OATS","Highly Nutritious from Nestle",
(select CUS_ID from customer where CUS_NAME="NEHA")),
(5,"HARRY POTTER","Best Collection of all time by J.K Rowling",
(select CUS_ID from customer where CUS_NAME="AAKASH")),
(6,"MILK","1L Toned MIlk",
(select CUS_ID from customer where CUS_NAME="NEHA")),
(7,"Boat EarPhones","1.5Meter long Dolby Atmos",
(select CUS_ID from customer where CUS_PHONE="9994562399")),
(8,"Jeans","Stretchable Denim Jeans with various sizes and color",
(select CUS_ID from customer where CUS_PHONE="7895999999")),
(9,"Project IGI","compatible with windows 7 and above",
(select CUS_ID from customer where CUS_PHONE="9785463215")),
(10,"Hoodie","Black GUCCI for 13 yrs and above",
(select CUS_ID from customer where CUS_PHONE="7895999999")),
(11,"Rich Dad Poor Dad","Written by RObert Kiyosaki",
(select CUS_ID from customer where CUS_NAME="AAKASH")),
(12,"Train Your Brain","By Shireen Stephen",
(select CUS_ID from customer where CUS_NAME="AAKASH"));
SELECT * FROM product;
